apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: dev
  name: ken-view
rules:
- apiGroups: ["", "apps", "extensions"]
  resources: ["pods", "deployments"]
  verbs: ["list", "get", "watch"]
