kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: dev
  name: ken-view
rules:
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["pods", "deployments"]
  verbs: ["list", "get", "watch"]
