apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ken-rolebinding
  namespace: dev
subjects:
- kind: ServiceAccount
  namespace: dev
  name: ken
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: ken-view 
  apiGroup: rbac.authorization.k8s.io
