kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ken-rolebinding
subjects:
- kind: ServiceAccount
  namespace: dev
  name: ken
  apiGroup: ""
roleRef:
  kind: Role
  name: ken-view 
  apiGroup: rbac.authorization.k8s.io
