kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ken-clusterrolebinding
subjects:
- kind: ServiceAccount
  namespace: dev
  name: ken
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: ken-view 
  apiGroup: ""
