apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 100%
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: twk8s/homework:my_nginx
# --- BEGIN ---
        readinessProbe:
          httpGet:
            path: /index.html
            port: 8000
# --- END ---
# --- START ---
        livenessProbe:
          tcpSocket: { port: 8000 }
# --- END ---
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: app
          mountPath: /var/www/app
      volumes:
      - name: app
        emptyDir: {}
      initContainers:
      - name: init-web
        image: busybox:1.31
        command: ['sh', '-c', 'wget -O- https://raw.githubusercontent.com/express42/otus-platform-snippets/master/Module-02/Introduction-to-Kubernetes/wget.sh | sh']
        volumeMounts:
        - name: app
          mountPath: /app

